{"uuid": "5749e676-bc9c-42a6-8969-5b1ebf49c7f3", "children": ["aa720416-3baa-4de5-9376-a5f937993425"], "befores": [{"name": "a_login", "status": "broken", "statusDetails": {"message": "requests.exceptions.SSLError: HTTPSConnectionPool(host='10.10.10.121', port=4500): Max retries exceeded with url: /UAMS/auth?username=admin (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))\n", "trace": "  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\D\\api_auto_test\\api_auto_test\\conftest.py\", line 80, in a_login\n    return login(user['username'])\n  File \"D:\\D\\api_auto_test\\api_auto_test\\conftest.py\", line 15, in login\n    resp = requests.request(method='POST',\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\wangsihan\\AppData\\Roaming\\Python\\Python38\\site-packages\\requests\\adapters.py\", line 517, in send\n    raise SSLError(e, request=request)\n"}, "start": 1702886511649, "stop": 1702886511656}], "start": 1702886511649, "stop": 1702886511717}